sudo: false
dist: trusty
language: node_js
node_js:
  - "13"
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: docs
install:
  - npm install
branches:
  only:
    - docs
