name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Jekyll site.
        uses: meitar/jekyll-builder-for-github-pages-action@v1
        with:
          secret_gh_pages_api_token: ${{ secrets.ACCESS_TOKEN }}
          pre_build_commands: |
            npm install
